apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    # Full permissions for the admin role to sync and manage all applications
    p, role:admin, *, */*, allow
