apiVersion: v1
kind: Service
metadata:
  name: basic-app-service
  namespace: web-app
spec:
  selector:
    app: basic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
